version: "3.8"

services:
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.tests
    environment:
      WAIT_HOSTS: server:80
      APP_HOSTNAME: server
    networks:
      - test
  logstash:
    image: logstash:7.8.0
    container_name: log
    environment:
      discovery.seed_hosts: logstash
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - ./logstash/pipeline/logstash-nginx.config:/usr/share/logstash/pipeline/logstash-nginx.config
      - ./logstash/nginx.log:/home/nginx.log
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "5044:5044"
      - "9600:9600"
    depends_on:
      - elasticsearch
    networks:
      - elastic
  server:
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: [ "CMD", "curl", "http://server/" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    ports:
      - "80:80"
    networks:
      - test
networks:
  test:


