version: "3.8"

services:
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.test
    environment:
      WAIT_HOSTS: server:80
    networks:
      - test
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - test
networks:
  test:

