version: "3.8"

services:
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.test
    environment:
      WAIT_HOSTS: server:80
    ports:
      - "8080:80"
    networks:
      - test
  server:
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: [ "CMD", "curl", "http://localhost/" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    ports:
      - "80:80"
    networks:
      - test
networks:
  test:

