version: "3.8"

services:
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.test
    environment:
      WAIT_HOSTS: server:80
    networks:
      - test
  server:
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: [ "CMD", "curl", "http://server/" ]
      # test: [ "CMD", "curl", "http://localhost/" ]
      # both server and local host work bc 80:80 maps localhost:80 to server:80 so is the host performing the healthcheck?
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    ports:
      - "80:80"
    networks:
      - test
networks:
  test:

