FROM ubuntu:latest AS build-env
COPY curl-script.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/curl-script.sh
RUN apt-get update
RUN apt-get install curl wget -y
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.3/wait /wait
RUN chmod +x /wait
CMD /wait && curl-script.sh

