version: "3.8"

services:
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.tests
    environment:
      WAIT_HOSTS: server:3000
      APP_HOSTNAME: server:3000
    networks:
      - test
  server:
    build:
      context: .
      dockerfile: Dockerfile.development
    healthcheck:
      test: [ "CMD", "wget", "-qO", "/dev/null", "http://server:3000/" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    ports:
      - "80:3000"
    networks:
      - test
networks:
  test:

